# Generated by Django 3.2.13 on 2023-08-06 16:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0002_basketitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
    ]
